targets:
  $default:
    builders:
      riverpod_generator|riverpod_generator:
        generate_for:
          - lib/**.dart

      mockito|mockBuilder:
        generate_for:
          - test/**.dart