// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_blog_app/test/features/home/controllers/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_blog_app/common/dao/blog_dao.dart' as _i2;
import 'package:flutter_blog_app/common/repositories/blog_repository.dart'
    as _i3;
import 'package:flutter_blog_app/models/index.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBlogDAO_0 extends _i1.SmartFake implements _i2.BlogDAO {
  _FakeBlogDAO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BlogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogRepository extends _i1.Mock implements _i3.BlogRepository {
  MockBlogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BlogDAO get dao =>
      (super.noSuchMethod(
            Invocation.getter(#dao),
            returnValue: _FakeBlogDAO_0(this, Invocation.getter(#dao)),
          )
          as _i2.BlogDAO);

  @override
  _i4.Future<List<_i5.BlogPost>> fetchBlogs({
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlogs, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i5.BlogPost>>.value(<_i5.BlogPost>[]),
          )
          as _i4.Future<List<_i5.BlogPost>>);

  @override
  _i4.Future<_i5.BlogPost?> fetchBlogById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlogById, [id]),
            returnValue: _i4.Future<_i5.BlogPost?>.value(),
          )
          as _i4.Future<_i5.BlogPost?>);

  @override
  _i4.Future<void> addBlog({
    required _i5.BlogPost? blog,
    required List<_i5.Images>? images,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addBlog, [], {#blog: blog, #images: images}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBlog(_i5.UpdateBlogPayload? payload) =>
      (super.noSuchMethod(
            Invocation.method(#updateBlog, [payload]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteBlog(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlog, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteMultipleBlogs(Set<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultipleBlogs, [ids]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.BlogPost>> searchBlogs(
    String? query, {
    required dynamic limit,
    required dynamic offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchBlogs,
              [query],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<_i5.BlogPost>>.value(<_i5.BlogPost>[]),
          )
          as _i4.Future<List<_i5.BlogPost>>);
}
