// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_blog_app/test/common/repositories/blog_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_blog_app/common/dao/blog_dao.dart' as _i3;
import 'package:flutter_blog_app/core/database/database.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BlogDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogDAO extends _i1.Mock implements _i3.BlogDAO {
  MockBlogDAO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get databaseHelper =>
      (super.noSuchMethod(
            Invocation.getter(#databaseHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#databaseHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<void> insertBlog({
    required Map<String, dynamic>? blog,
    required List<Map<String, dynamic>>? images,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertBlog, [], {#blog: blog, #images: images}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getBlogPosts({
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBlogPosts, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getImagesByBlogIds(
    List<String>? blogIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getImagesByBlogIds, [blogIds]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getImagesByBlogId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getImagesByBlogId, [id]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getBlog(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBlog, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertImage(Map<String, dynamic>? imageMap) =>
      (super.noSuchMethod(
            Invocation.method(#insertImage, [imageMap]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> updateBlog(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateBlog, [id, data]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> deleteSavedImages({
    required String? blogId,
    required List<String>? savedImages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedImages, [], {
              #blogId: blogId,
              #savedImages: savedImages,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteBlog(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlog, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteMultiple(Set<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultiple, [ids]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchBlogs(
    String? query, {
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchBlogs,
              [query],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
